### ISSUE TITLE
Mbed mic 센서로부터 음성 데이터 수집

### ISSUE THREAD

**Issue by JoHwanhee** [seoul-hardware-hackerton/eslow-mycaps-project#9]
#3

**Comment by JoHwanhee** [comment]
- iot01a1 보드에 mic 센서가 있긴한데, 관련 드라이버 소스를 도저히 찾을 수 없음.
- 구글링해보면 나오는 소스들은 다 다른 보드에서 사용되는 소스들 뿐... 
- 우선 주문한 max4665 센서로 테스트할 예정

**Comment by LenKIM** [comment]
@JoHwanhee 
요렇게 멘션하면 나한테 노티올거야

**Comment by JoHwanhee** [comment]
@LenKIM 갈 길을 잃었어요...... 이 양반 도대체 어떻게 한거지 https://www.youtube.com/watch?v=DffZVyksYi4

**Comment by JoHwanhee** [comment]
오늘 트라이할 것

https://www.instructables.com/id/Ethernet-Voice-Streaming/

**Comment by JoHwanhee** [comment]
동작 되는 마이크 센서  이미지

![image](https://user-images.githubusercontent.com/12796737/54882004-1d4c1900-4e99-11e9-8a71-c6979ef260d1.png)

**Comment by JoHwanhee** [comment]
@LenKIM  PWM data 서버로 전송 테스트 완료, play하면 아무소리도 안나옴!!!!!!!

![image](https://user-images.githubusercontent.com/12796737/54883998-f13b9280-4eae-11e9-8704-f99dcb383393.png)


![image](https://user-images.githubusercontent.com/12796737/54884691-55faeb00-4eb7-11e9-8fb9-948194cfab56.png)

**Comment by LenKIM** [comment]
프로젝트 완료.
